# As stolen from the travis site... 
language: python
python:
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt

before_script:
 - pycodestyle --ignore=E501 *.py
 - pyflakes *.py
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below

# Add our dbs
services:
 - mysql

